name: 'Slack Notifier'
description: 'Send your notifications to slack'
inputs:
  PERSONAL_ACCESS_TOKEN:
    description: 'Personal access token to read notifications'
    required: true
  SLACK_URL:
    description: 'Slack incoming webhook URL'
    required: true
runs:
  using: 'node12'
  main: 'index.js'