name: Post to Slack

on:
  push:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  find-notifications:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Find Notifications
        uses: ./
    
