name: Post to Slack

on:
  push:
  schedule:
    - cron: "10,25,40,55 15-23,0-3 * * 1-5"

jobs:
  find-notifications:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Set Since
        id: get-since
        run: |
          echo "::set-output name=since::$(cat ./last-touched)"

      - name: Find Notifications
        uses: ./
        with:
          SLACK_URL: ${{ secrets.SLACK_URL }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          SINCE: ${{ steps.get-since.outputs.since }}
      
      - name: Update Since
        run: |
          date --iso-8601=seconds --utc > ./last-touched 

          git config --local user.email "scheduler@cdbdesign.net"
          git config --local user.name "cdb Scheduler [automated]"
          
          git add ./last-touched
          git commit -m "update last-touched"
          git push
    
