name: Post to Slack

on:
  push:
  schedule:
    - cron: "* * * * *"

jobs:
  find-notifications:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Find Notifications
        uses: ./
        with:
          SLACK_URL: ${{ secrets.SLACK_URL }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    
