name: Post to Slack

on:
  push:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  find-notifications:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          echo "PAT: $AQWS"
        env:
          AQWS: ${{ secrets.PERSONAL_ACCESS_TOKEN}}
      - name: Find Notifications
        uses: ./
        env:
          SLACK_URL: ${{ secrets.SLACK_URL }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    
