name: Testing check suite event
on:
  check_suite:
    #types: [ completed ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
